### ISSUE TITLE
可能是因为torch版本引起的报错？“2.2.1-Pytorch编写Transformer”

### ISSUE THREAD

**Issue by roki1031** [datawhalechina/transformers-quick-start-zh#38]
你好！
      在学习到时候发现一个bug，如下图所示：
![image](https://user-images.githubusercontent.com/52522880/135754297-34434008-fd73-4cc2-80c5-0111e1237c29.png)
如果tgt不改成torch.LongTensor格式的话，就会在“贪婪解码”的代码部分报错“scatter_(): Expected dtype int64 for index.”。

**Comment by erenup** [comment]
感谢指出！
