### ISSUE TITLE
transformer里面的attention代码和前文讲的论文公式不一样啊？有一点懵了

### ISSUE THREAD

**Issue by mapleleaf6** [datawhalechina/transformers-quick-start-zh#39]
既然forward的输入已经是Q,K,V了，为什么还要
Q = self.w_q(query)
K = self.w_k(key)
V = self.w_v(value)
这一步啊？
Q,K,V的句子的词的数量为啥不一样啊？

**Comment by mapleleaf6** [comment]
是编程的时候做的经验化处理还是啥啊？？？？

**Comment by erenup** [comment]
可以具体到哪一章哪一小节嘛？

**Comment by erenup** [comment]
> 
对于Attention而言Q和K对应的token的数量可以不一样哈，单在transformer 应该是一样的。
